import "../Home.css";

export const Home = () => {
  return (
    <div className="container-home">
      <h1>Welcome to 24x7 shopping store.</h1>

      <section>
        <div>offers</div>
        <div className="section">
          <button>shop Now</button>
        </div>
      </section>
      <h3>
        This is a non-profitable site .Any income generated by the site is spend
        in further development of this sites and social causes.
      </h3>
      <p>
        Order anything anytime anyday and the process to delevring it to you
        within 5 hours{" "}
      </p>
      <p>
        The goods reach to you in the faster and safest way to you than anyother
        online mart.
      </p>
      <h3>Special thanks to</h3>
      <p>
        Thanks to all the developer and the contributer to help in building this
        site.
      </p>
    </div>
  );
};
