import { v4 as uuidv4 } from "uuid";

import {
  YouCanWIN,
  TheHauntingofHillHouse,
  TheAlchemist,
  ToKillAMockingbird,
  b1984,
  PridePrejudice,
  TheGreatGatsby,
  HarryPotter,
  TheCatcherInTheRye,
  MobyDick,
  TheLordOfTheRings,
  TheChroniclesOfNarnia,
  ThePictureOfDorianGray,
} from "../../assets/image/index";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuidv4(),
    count: 0,
    image: YouCanWIN,
    display: true,
    title: "You Can WIN",
    author: "Shiv Khera",
    price: "5000",
    categoryName: "non-fiction",
  },

  {
    _id: uuidv4(),
    count: 0,
    image: TheHauntingofHillHouse,
    display: true,
    title: "The Haunting of Hill House",
    author: "Shirley Jackson",
    price: "3000",
    categoryName: "horror",
  },
  {
    _id: uuidv4(),
    count: 0,
    image: TheAlchemist,
    display: true,
    title: "The Alchemist",
    author: "Paulo Coelho",
    price: "1000",
    categoryName: "Philosophy",
  },

  {
    _id: uuidv4(),
    count: 0,
    image: ToKillAMockingbird,
    display: true,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    price: "5845",
    categoryName: "Fiction",
  },
  {
    _id: uuidv4(),
    count: 0,
    image: b1984,
    display: true,
    title: "1984",
    author: "George Orwell",
    price: "4546",
    categoryName: "Fiction",
  },
  {
    _id: uuidv4(),
    count: 0,
    image: PridePrejudice,
    display: true,
    title: "Pride and Prejudice",
    author: "Jane Austen",
    price: "4587",
    categoryName: "Romance",
  },
  {
    _id: uuidv4(),
    count: 0,
    image: TheGreatGatsby,
    display: true,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    price: "8567",
    categoryName: "Fiction",
  },
  {
    _id: uuidv4(),
    count: 0,
    image: HarryPotter,
    display: true,
    title: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    price: "5465",
    categoryName: "Fantasy",
  },
  {
    _id: uuidv4(),
    count: 0,
    image: TheCatcherInTheRye,
    display: true,
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    price: "4546",
    categoryName: "Fiction",
  },
  {
    _id: uuidv4(),
    count: 0,
    image: MobyDick,
    display: true,
    title: "Moby-Dick",
    author: "Herman Melville",
    price: "8576",
    categoryName: "Adventure",
  },
  {
    _id: uuidv4(),
    count: 0,
    image: TheLordOfTheRings,
    display: true,
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    price: "7586",
    categoryName: "Adventure",
  },
  {
    _id: uuidv4(),
    count: 0,
    image: TheChroniclesOfNarnia,
    display: true,
    title: "The Chronicles of Narnia",
    author: "C.S. Lewis",
    price: "2236",
    categoryName: "Fantasy",
  },
  {
    _id: uuidv4(),
    count: 0,
    image: ThePictureOfDorianGray,
    display: true,
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    price: "8721",
    categoryName: "Fiction",
  },
];
